version: '3.9'

services:
  mysql:
    image: mysql:8.0
    networks:
      - backend
    container_name: mysql
    ports:
      - "${MYSQL_PORT}:${MYSQL_PORT}"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - mysql_data:/var/lib/mysql

  django:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - backend
    container_name: django_app
    ports:
      - "${DJANGO_PORT}:${DJANGO_PORT}"
    environment:
      DJANGO_PORT: ${DJANGO_PORT}
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

networks:
  backend:
    driver: bridge
    name: network_proyecto_backend

volumes:
  mysql_data:
    