# Generated by Django 4.2.7 on 2024-12-03 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30)),
                ('fecha_inicio', models.DateField()),
                ('fecha_termino', models.DateField()),
                ('descripcion', models.TextField(blank=True, max_length=255)),
                ('tipo', models.CharField(choices=[('Vac', 'Vacaciones'), ('Fer', 'Feriado'), ('SusAct', 'Suspension de Actividades'), ('SusActPM', 'Suspension de Actividades PM'), ('PerLec', 'Periodo Lectivo'), ('SusEval', 'Suspensión de Evaluaciones'), ('Cer', 'Ceremonia'), ('EDDA', 'EDDA'), ('Eval', 'Evaluación'), ('Ayu', 'Ayudantías'), ('HitAca', 'Hito Académico'), ('SecAca', 'Secretaría Académica'), ('OAI', 'OAI')], max_length=40)),
                ('segmento', models.ManyToManyField(to='auth.group')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
            },
        ),
    ]
